### ISSUE TITLE
Invoke in dev mode

### ISSUE THREAD

**Issue by Shujee** [fengxinming/vite-plugins#19]
Can we call it during "dev" sessions? I need to perform copying of a file not only in `npm run build`, but also in `npm run dev` sessions and then perform some static transformations, but it looks like the plugin works in build, but not in dev mode.

**Comment by fengxinming** [comment]
@Shujee which plugins can not work in dev mode?

**Comment by Shujee** [comment]
Many of them, e.g. [vite-plugin-cp](https://github.com/fengxinming/vite-plugins/tree/main/packages/vite-plugin-cp) and [vite-plugin-transform](https://github.com/Silksofthesoul/vite-plugin-transform). I finally had to write my own plugin, but now I'm facing the opposite problem. It now runs in dev mode, but not with `npm run build`.

**Comment by Shujee** [comment]
BTW, the code of my plugin is available here: https://stackoverflow.com/a/76971759/1137199
