### ISSUE TITLE
Hey! 👋

### ISSUE THREAD

**Issue by caoxiemeihao** [fengxinming/vite-plugins#4]
My bro! [vite-plugin-external](https://www.npmjs.com/package/vite-plugin-external) 能交给我维护不，现在 npm 上面的包实现的 external 都偏重了点

**Comment by fengxinming** [comment]
我实现已经很轻量级了，每个人的实现思路不一样，我利用的都是vite的原生能力，我看你已经提交了一个包了。我写这个之前是因为用了 [vite-plugin-externals](https://www.npmjs.com/package/vite-plugin-externals) 遇到了一个问题我绕不过去，所以才新写一个。

**Comment by caoxiemeihao** [comment]
哈哈哈，好的；我去找 [vite-plugin-externals](https://www.npmjs.com/package/vite-plugin-externals)
